### ISSUE TITLE
Channel category support?

### ISSUE THREAD

**Issue by haworthia-hime** [ozankaraali/QiTV#11]
Hello! I'm happy to find a player that supports STB on PC! If it's not too much to ask, would you be interested in possibly adding support for channel categories? I know of some other IPTV players that do, so just a suggestion! Thank you.

**Comment by ozankaraali** [comment]
Hi,

Glad to hear that works for you. I am busy recently, if someone pushes a PR, I can merge, if not you should be waiting a bit long, maybe I can take a look whenever I am available. It was a design choice back then since I was not using categories, but now I am okay if someone wants to add that.

**Comment by pcjco** [comment]
Hi,
If you look at https://github.com/pcjco/QiTV/commit/c271db37b48e3a250cf7eca2cd64d973a0b6bca1 I have made a try to deal with VOD/Series by using pagination as retrieved on STB Portal (applicable for STB provider only).
Also channels are sorted in categories (also applicable for STB provider only).
Navigation is done using First/Prev/Next/Last Page and Back button.

**Comment by ozankaraali** [comment]
> Hi, If you look at [pcjco@c271db3](https://github.com/pcjco/QiTV/commit/c271db37b48e3a250cf7eca2cd64d973a0b6bca1) I have made a try to deal with VOD/Series by using pagination as retrieved on STB Portal (applicable for STB provider only). Also channels are sorted in categories (also applicable for STB provider only). Navigation is done using First/Prev/Next/Last Page and Back button.

Thanks @pcjco I managed to run, but I already did some changes before looking at yours, I need a bit of a time to merge these both, cheers!

**Comment by ozankaraali** [comment]
I believe with the release 1.5.2, it should be fully supported now. Thanks @pcjco 
https://github.com/ozankaraali/QiTV/releases/tag/v1.5.2
