### ISSUE TITLE
installation on macos

### ISSUE THREAD

**Issue by grgmll** [ozankaraali/QiTV#2]
HI,
installation on macos silicon M2 fails

Thanks

**Comment by ozankaraali** [comment]
Hi,
Sad to hear but I am not reading minds. Explain your issue.
Thanks.

**Comment by grgmll** [comment]
HI,
I tried to install the qitv-macos-universal.zip 1.4.2
but after the installation it tells me that the file is damaged, version 1.1.2 of PiTV also does the same while 1.1.1 works

**Comment by ozankaraali** [comment]
Hi, you put the app into /Applications, then you try to open it and then go Preferences, Privacy and Allow the app. It should work. It will say it is damaged because I don’t sign the apps with a proper signature. Just do a self allow.

**Comment by grgmll** [comment]
no it doesn't work, it tells me that the file is damaged, I allow the permissions as I do for version 1.1.1 of PiTV

**Comment by ozankaraali** [comment]
Does the intel version work, can you try?

**Comment by grgmll** [comment]
sorry I only have a macbook with arm64 silicon M2

**Comment by ozankaraali** [comment]
I know, download the intel version to your computer and try with that. It should work.

**Comment by grgmll** [comment]
it opens but closes immediately

**Comment by ozankaraali** [comment]
Thanks for the heads up, what you should do, remove the existing QiTV first from the /Applications (so it should remove the cache of Launchpad, you should not be seeing), then download the following version and try again. Let me know if this fixes.
https://github.com/ozankaraali/QiTV/releases/tag/v1.4.3

**Comment by grgmll** [comment]
Yes, this version works, it opens but the app does not install

**Comment by ozankaraali** [comment]
There is no installer, you drag the app inside of the Applications and that will be it. I am closing this issue.

**Comment by grgmll** [comment]
sorry, it's true with all the tests I did I got confused

**Comment by ozankaraali** [comment]
No worries, that’s fine if everything works correctly now.

**Comment by grgmll** [comment]
thanks for solving my problem
