### ISSUE TITLE
install failed on win11

### ISSUE THREAD

**Issue by myrshfrs** [ozankaraali/QiTV#3]
![屏幕截图 2024-06-18 004047](https://github.com/ozankaraali/QiTV/assets/6205312/93f592aa-de0d-4592-9261-22703ea6e042)

**Comment by ozankaraali** [comment]
It could be your provider, proxy, firewall settings. I cannot reproduce, try the default bundled playlist to see if that works.

**Comment by myrshfrs** [comment]
thank you. solved. it's my proxy problem.

**Comment by myrshfrs** [comment]
it seems that qitv doesn't follow system proxy setting on win11

**Comment by ozankaraali** [comment]
Probably, I never had a proxy concern when designing this app.

**Comment by myrshfrs** [comment]
i am in China and because of the GFW, some sites are blocked.

**Comment by myrshfrs** [comment]
thank you. i am using pitv now. it works well.

**Comment by ozankaraali** [comment]
@myrshfrs can you try this one and see if it helps with your proxy? https://github.com/ozankaraali/QiTV/releases/tag/v1.4.4

**Comment by myrshfrs** [comment]
> @myrshfrs can you try this one and see if it helps with your proxy? https://github.com/ozankaraali/QiTV/releases/tag/v1.4.4

This update solves the “unhandled expectation” problem. Thank you~
