### ISSUE TITLE
Tebrik ve İstek

### ISSUE THREAD

**Issue by Nikreb35** [ozankaraali/QiTV#7]
Merhaba,

İptv - Stalker projeleriniz için sizi tebrik ederim. Gayet stabil çalışıyor.
Android tv box'lar için .apk olarak geliştirme imkanınız var mı?
Bu projeyi gerçekleştirirseniz memnuniyetle kullanırım.

İyi çalışmalar.

**Comment by ozankaraali** [comment]
Öncelikle feedback için teşekkürler, beğendiğinize sevindim.

Hayır, projeyi keyfi olarak geliştiriyorum, Android’de Tivimate ya da OTTNav gibi projeler hali hazırda mevcut ve yeterli hissettiriyor.

Sorunuz için teşekkürler, iyi günler dilerim.
