### ISSUE TITLE
m3u problemi

### ISSUE THREAD

**Issue by Nikreb35** [ozankaraali/QiTV#8]
Merhaba,

Programı MAC Portal olarak denemiştim. sorun yok.
Ama m3u olarak kaydettiğim listeleri açamıyorum.
Kanal listesi geliyor, ama kanala tıklayınca açılmıyor.
Linkte sorun olabileceğini düşünüp başka playerlarda denedim sorun çıkmadı.
Yani şuanda m3u oynatmıyor. MAC'te sorun yok.
Herhangi bir hata kodu çıkmıyor ama kanal da açılmıyor. tepkisiz.

**Comment by ozankaraali** [comment]
playlistinizin reproduce edilebilecek kadar örneğine ihtiyacım var, program açıldığında gelen liste iptv-org’un m3u listesi ve o çalışıyor, o yüzden sizin listenizi görmeden yorum yapamam
